name       : perl-b-hooks-endofscope
version    : 0.21
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/E/ET/ETHER/B-Hooks-EndOfScope-0.21.tar.gz : 90f3580880f1d68b843c142cc86f58bead1f3e03634c63868ac9eba5eedae02c
license    : Artistic-2.0
component  : programming.perl
summary    : Execute code after a scope finished compilation
description: |
    Execute code after a scope finished compilation
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
