name       : perl-b-hooks-endofscope
version    : '0.24'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/B-Hooks-EndOfScope-0.24.tar.gz : 03aa3dfe5d0aa6471a96f43fe8318179d19794d4a640708f0288f9216ec7acc6
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Execute code after a scope finished compilation
description: |
    Execute code after a scope finished compilation
builddeps  :
    - perl-module-implementation
    - perl-sub-exporter-progressive
    - perl-variable-magic
rundeps    :
    - perl-module-implementation
    - perl-sub-exporter-progressive
    - perl-variable-magic
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
