name       : perl-b-hooks-endofscope
version    : '0.26'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/E/ET/ETHER/B-Hooks-EndOfScope-0.26.tar.gz : 39df2f8c007a754672075f95b90797baebe97ada6d944b197a6352709cb30671
homepage   : https://metacpan.org/pod/B::Hooks::EndOfScope
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : B::Hooks::EndOfScope - Execute code after a scope finished compilation
description: |
    This module allows you to execute code when perl finished compiling the surrounding scope.
builddeps  :
    - perl-module-implementation
    - perl-sub-exporter-progressive
    - perl-variable-magic
rundeps    :
    - perl-module-implementation
    - perl-sub-exporter-progressive
    - perl-variable-magic
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
